### ISSUE TITLE
[BUG] Screen: temperature options disappear?

### ISSUE THREAD

**Issue by chrislader** [EdddieN/machinon-domoticz_theme#313]
When going to the Temperature overview, some of the options disappear after some seconds (propably when updates are received)

It includes the 3 dots and graph bars (log). 

![image](https://user-images.githubusercontent.com/40333466/71645281-45915f80-2cd6-11ea-9ed8-3d770fb22de7.png)

Latest beta: 1.10.2
and latest domoticz beta

Strange thing is that they appear and disappear after a few minutes.
And it's not all of the sensors. Some stay. 

I noticed that it has something to do with time displayed as "x ago" versus the actual timestamp. The options disappear as well as the info when the sensor was last updated.

**Comment by davidlb** [comment]
Thanks for your report, I'll check it next week.

**Comment by davidlb** [comment]
I cannot reproduce it, it has probably fixed in the beta branch as many parts of the code have been rewritten.

**Comment by chrislader** [comment]
> I cannot reproduce it, it has probably fixed in the beta branch as many parts of the code have been rewritten.

Hi David,
Although you can not reproduce it, it is a bug... I have cleared chache, updated latest beta domoticz and switched to beta branch machinon.

Even with latest Machinon beta v1.12 beta it still happens.

Version: 4.11605 (domoticz, beta)

Are you sure it does not happen? It has been around for some versions now. like a few months. none of the updates seem to fix it.

**Comment by davidlb** [comment]
Hi @chrislader, good news, I've finally able to reproduce it and I have a fix for it :)

**Comment by davidlb** [comment]
Can you update to last beta?

**Comment by chrislader** [comment]
> Can you update to last beta?

Hi David, I just updated, but it looks like the bug is still there.
v1.13 beta
I cleared cache as well and reset all theme settings.

Noticed that the camera's are also gone from dashboard. This was also the case for beta 1.12

![image](https://user-images.githubusercontent.com/40333466/72285316-2504c600-3643-11ea-9e03-5310bc988575.png)

**Comment by josemi73** [comment]
Camera section in dashboard (beta) is missing for me too.

**Comment by scfrancis** [comment]
hello, i also have camera problem on dashboard... Any idea ?

**Comment by davidlb** [comment]
damn, you're right, camera does not work and still have the issue with temperatures...
I keep working on it to provide a fix on both.

**Comment by scfrancis** [comment]
> damn, you're right, camera does not work and still have the issue with temperatures...
> I keep working on it to provide a fix on both.

Thanks for your help

**Comment by davidlb** [comment]
Can you retry with these 2 fixes? (one for temperatures and one for cameras)
If it's OK, I'll release a new version.

**Comment by scfrancis** [comment]
FIX display of Cameras = OK !!!!!!!!!!!!!!

**Comment by josemi73** [comment]
Cameras Ok also for me. Thank you!

**Comment by chrislader** [comment]
Same here, great job on the fix!

**Comment by davidlb** [comment]
@chrislader is it also OK now for the temperature options?
If yes, I release a new version.

**Comment by chrislader** [comment]
Yes, you can release a new version. Thanks for solving the issue.

Although I use grafana for my monitoring, it is sometimes easy to view the temp sensors directly in domoticz

Fixed now!
